version: "3.9"
services:
  backend:
    image: place-quest-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - JWT_SECRET=secret
      - DB_HOST=db

  db:
    image: postgres:14-alpine
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  db-data: